yolo_model:

  config_file:
    name: data1204_net.cfg
  weight_file:
    name: data1211_net_5000.weights
  threshold:
    value: 0.2
  detection_classes:
    names:
      - up
      - up_on
      - e18
      - e18_on
