arm_joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

interaction_arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - arm_joint_0 
      - arm_joint_1 
      - arm_joint_2 
      - arm_joint_3 
      - arm_joint_4 
      - arm_joint_5 

neck_controller:
    type: position_controllers/JointPositionController
    publish_rate: 50
    base_frame_id: base_link
    joint : neck_joint_0

